name:                avarice
version:             0.3.1.2
synopsis:            A AIO Translation and .iso Editing Library
description:         A tool for translating video games and applications .iso via scripts and ImageDiff
github:              MilesLitteral/avarice
homepage:            https://github.com/MilesLitteral/avarice
bug-reports:         https://github.com/MilesLitteral/avarice/issues
license:             MIT
category:            Application
maintainer:          Mandaloe2@gmail.com

extra-doc-files:
- ChangeLog.md

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- lens
- monomer >= 1.5.1.0 && < 1.7
- text
- mtl
# data processing
- xml
- stm
#OS Handling
- tinyfiledialogs

default-extensions:
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleInstances 
  #- GeneralizedNewtypeDeriving
  #- DeriveAnyClass
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - NumericUnderscores
  - OverloadedRecordDot
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables

flags:
  examples:
    description: Whether to build the example executables. Off by default because they are not usually wanted.
    manual: true
    default: false
  iso:
    description: Build executables that demonstrate ImageDiff functionality
    manual: true
    default: false

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -optl-mconsole -optl-mwindows

library:
  source-dirs: src
  generated-other-modules: Paths_avarice

executables:
  example-basic:
    source-dirs: examples/basic
    main: Main.hs
    buildable: true
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - avarice
      - time
    #when:
    #  - condition: flag(examples)
    #    then:
    #      buildable: true
    #    else:
    #      buildable: false
  example-iso:
    source-dirs: examples/iso
    main: Main.hs
    buildable: true
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - avarice
      - time
    when:
     - condition: flag(iso)
       then:
         buildable: true
       else:
         buildable: false
  example-big-grid:
    source-dirs: examples/big-grid
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - avarice
      - tinyfiledialogs
    when:
      - condition: flag(examples)
        then:
          buildable: true
        else:
          buildable: false
  example-resizing-cells:
    source-dirs: examples/resizing-cells
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - avarice
      - random
    when:
      - condition: flag(examples)
        then:
          buildable: true
        else:
          buildable: false

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bytestring
      - data-default
      - avarice
      - mtl
      - stm